### PR TITLE
Add icalendar dependency

### PR DESCRIPTION
**Pull request by funnelfiasco**
schedule_convert needs python2-icalendar

### CODE REVIEW

**Comment by pavel-slama** [comment]
Nope - not gonna work on rhel atm. I need to build specifically python2-* package first.

**Comment by funnelfiasco** [comment]
Hm, I was worried about that. Would changing it to something like
`Requires: python2dist(icalendar)`
work on RHEL? That way it's dependent on the capability, not the package name.

**Comment by pavel-slama** [comment]
> Hm, I was worried about that. Would changing it to something like
> `Requires: python2dist(icalendar)`
> work on RHEL? That way it's dependent on the capability, not the package name.

It doesn't - depends on what capabilities the packages provide and apparently it's not in current available rhel rpm. I don't have time for this right now, but I planned some time in next sprint. There are other dependencies for icalendar package - I'll have to rebuild some of them, tag some other into our brew build root - not really that straightforward.

**Comment by funnelfiasco** [comment]
Okay. I'm in no hurry here, since I manually `dnf install`ed python2-icalendar. If I can help with future work, let me know.

**Comment by pavel-slama** [comment]
@funnelfiasco Ok I built all the needed packages into our internal repos for rhel. Please add icalendar to requirements.txt as well and I'll merge it.

**Pull request merged**
